# Generated by Django 6.0.5 on 2026-05-21 21:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Kategori Adı')),
                ('order_index', models.IntegerField(default=0, help_text='Küçük sayı önce gösterilir.', verbose_name='Sıralama')),
            ],
            options={
                'verbose_name': 'Kategori',
                'verbose_name_plural': 'Kategoriler',
                'ordering': ['order_index', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Ürün Adı')),
                ('description', models.TextField(blank=True, help_text='Müşteriye gösterilecek ürün detayı.', verbose_name='Açıklama/İçindekiler')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Fiyat (₺)')),
                ('image_url', models.URLField(blank=True, help_text='Örn: https://example.com/pide.jpg', verbose_name='Görsel Linki')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif (Menüde Göster)')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='menu.category', verbose_name='Kategori')),
            ],
            options={
                'verbose_name': 'Ürün',
                'verbose_name_plural': 'Ürünler',
                'ordering': ['category__order_index', 'name'],
            },
        ),
    ]
